package studymanage;

import java.awt.Font;

import javax.swing.*;

public class Adding extends JFrame{
	private static final long serialVersionUID = 13797L;
	JLabel recorder=new JLabel("记录号：");
	JLabel lessonnumber=new JLabel("课程号：");
	JLabel lessonname=new JLabel("课程名称：");
	JLabel schscore=new JLabel("学分：");
	JLabel classroom=new JLabel("教室：");
	JLabel tm=new JLabel("考试时间：");
	JLabel grades=new JLabel("成绩：");
	JButton sure=new JButton("确定添加");
	JLabel WARN=new JLabel();
	String name=null;
	JTextField jiluhao=new JTextField();
	JTextField kechenghao=new JTextField();
	JTextField kechengmingcheng=new JTextField();
	JTextField xuefen=new JTextField();
	JTextField jiaoshi=new JTextField();
	JTextField kaoshishijian=new JTextField();
	JTextField chengji=new JTextField();
	int wd=35,le=125,x=15,y=15;//宽度，长度，x和y轴
	Adding(String username){
		int i=0;
		AddSuringListener lisn=new AddSuringListener();
		Font ft1=new Font("宋体",Font.BOLD,24);
		Font ft2=new Font("宋体",Font.BOLD,32);
		Font ft3=new Font("宋体",Font.BOLD,36);
		Font ft4=new Font("宋体",Font.BOLD,20);
		setLayout(null);
		recorder.setBounds(x, i*wd+y, le, wd);
		recorder.setFont(ft1);
		jiluhao.setFont(ft4);
		jiluhao.setBounds(x+le+5, y+i*wd, 475-(x+le), wd-5);
		i++;
		lessonnumber.setFont(ft1);
		lessonnumber.setBounds(x, y+i*wd, le, wd);
		kechenghao.setFont(ft4);
		kechenghao.setBounds(x+le+5, y+i*wd, 475-(x+le), wd-5);
		i++;
		lessonname.setFont(ft1);
		lessonname.setBounds(x, y+i*wd, le, wd);
		kechengmingcheng.setFont(ft4);
		kechengmingcheng.setBounds(x+le+5, y+i*wd, 475-(x+le), wd-5);
		i++;
		schscore.setFont(ft1);
		schscore.setBounds(x, y+i*wd, le, wd);
		xuefen.setFont(ft4);
		xuefen.setBounds(x+le+5, y+i*wd, 475-(x+le), wd-5);
		i++;
		classroom.setFont(ft1);
		classroom.setBounds(x, y+i*wd, le, wd);
		jiaoshi.setFont(ft4);
		jiaoshi.setBounds(x+le+5, y+i*wd, 475-(x+le), wd-5);
		i++;
		tm.setFont(ft1);
		tm.setBounds(x, y+i*wd, le, wd);
		kaoshishijian.setFont(ft4);
		kaoshishijian.setBounds(x+le+5, y+i*wd, 475-(x+le), wd-5);
		i++;
		grades.setFont(ft1);
		grades.setBounds(x, y+i*wd, le, wd);
		chengji.setFont(ft4);
		chengji.setBounds(x+le+5, y+i*wd, 475-(x+le), wd-5);
		i++;
		WARN.setFont(ft2);
		WARN.setBounds(x, y+i*wd, 450, 50);
		i=i+2;
		sure.setFont(ft3);
		sure.setBounds(125,y+i*wd+10,250,50);
		sure.addActionListener(lisn);
		lisn.setUsername(username);
		lisn.setReg(this);
		add(recorder);
		add(jiluhao);
		add(schscore);
		add(xuefen);
		add(lessonnumber);
		add(kechenghao);
		add(lessonname);
		add(kechengmingcheng);
		add(classroom);
		add(jiaoshi);
		add(tm);
		add(kaoshishijian);
		add(grades);
		add(chengji);
		add(WARN);
		add(sure);
	}
}
